var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_install_1_1_data_object =
[
    [ "OxidEshopPackage", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_install_1_1_data_object_1_1_oxid_eshop_package.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_install_1_1_data_object_1_1_oxid_eshop_package" ]
];