var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_theme_1_1_bridge =
[
    [ "AdminThemeBridge", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_theme_1_1_bridge_1_1_admin_theme_bridge.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_theme_1_1_bridge_1_1_admin_theme_bridge" ],
    [ "AdminThemeBridgeInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_theme_1_1_bridge_1_1_admin_theme_bridge_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_theme_1_1_bridge_1_1_admin_theme_bridge_interface" ]
];