var namespace_oxid_esales_1_1_eshop_community_1_1_core_1_1_dao =
[
    [ "ApplicationServerDao", "class_oxid_esales_1_1_eshop_community_1_1_core_1_1_dao_1_1_application_server_dao.html", "class_oxid_esales_1_1_eshop_community_1_1_core_1_1_dao_1_1_application_server_dao" ],
    [ "ApplicationServerDaoInterface", "interface_oxid_esales_1_1_eshop_community_1_1_core_1_1_dao_1_1_application_server_dao_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_core_1_1_dao_1_1_application_server_dao_interface" ],
    [ "BaseDaoInterface", "interface_oxid_esales_1_1_eshop_community_1_1_core_1_1_dao_1_1_base_dao_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_core_1_1_dao_1_1_base_dao_interface" ]
];