var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_extension =
[
    [ "CacheResourcePlugin", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_extension_1_1_cache_resource_plugin.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_extension_1_1_cache_resource_plugin" ],
    [ "SmartyDefaultTemplateHandler", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_extension_1_1_smarty_default_template_handler.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_extension_1_1_smarty_default_template_handler" ]
];