var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_storage =
[
    [ "ArrayStorageInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_storage_1_1_array_storage_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_storage_1_1_array_storage_interface" ],
    [ "FileStorageFactoryInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_storage_1_1_file_storage_factory_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_storage_1_1_file_storage_factory_interface" ],
    [ "YamlFileStorage", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_storage_1_1_yaml_file_storage.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_storage_1_1_yaml_file_storage" ],
    [ "YamlFileStorageFactory", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_storage_1_1_yaml_file_storage_factory.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_storage_1_1_yaml_file_storage_factory" ]
];