var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_domain_1_1_review_1_1_view_data_object =
[
    [ "ReviewAndRating", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_domain_1_1_review_1_1_view_data_object_1_1_review_and_rating.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_domain_1_1_review_1_1_view_data_object_1_1_review_and_rating" ]
];