var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_logger_1_1_factory =
[
    [ "LoggerFactoryInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_logger_1_1_factory_1_1_logger_factory_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_logger_1_1_factory_1_1_logger_factory_interface" ],
    [ "MonologLoggerFactory", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_logger_1_1_factory_1_1_monolog_logger_factory.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_logger_1_1_factory_1_1_monolog_logger_factory" ]
];