var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_data_object =
[
    [ "ShopConfigurationSetting", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_data_object_1_1_shop_configuration_setting.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_data_object_1_1_shop_configuration_setting" ],
    [ "ShopSettingType", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_data_object_1_1_shop_setting_type.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_data_object_1_1_shop_setting_type" ]
];