var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_review_1_1_service_factory =
[
    [ "ReviewServiceFactory", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_review_1_1_service_factory_1_1_review_service_factory.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_review_1_1_service_factory_1_1_review_service_factory" ]
];