var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_legacy =
[
    [ "LegacySmartyEngine", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_legacy_1_1_legacy_smarty_engine.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_legacy_1_1_legacy_smarty_engine" ],
    [ "LegacySmartyEngineFactory", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_legacy_1_1_legacy_smarty_engine_factory.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_legacy_1_1_legacy_smarty_engine_factory" ],
    [ "LegacySmartyEngineInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_legacy_1_1_legacy_smarty_engine_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_smarty_1_1_legacy_1_1_legacy_smarty_engine_interface" ]
];