var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_transition_1_1_utility_1_1_exception =
[
    [ "AdminUserNotFoundException", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_transition_1_1_utility_1_1_exception_1_1_admin_user_not_found_exception.html", null ]
];