var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_templating_1_1_loader =
[
    [ "TemplateLoader", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_templating_1_1_loader_1_1_template_loader.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_templating_1_1_loader_1_1_template_loader" ],
    [ "TemplateLoaderInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_templating_1_1_loader_1_1_template_loader_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_templating_1_1_loader_1_1_template_loader_interface" ]
];