var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_logger_1_1_validator =
[
    [ "LoggerConfigurationValidatorInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_logger_1_1_validator_1_1_logger_configuration_validator_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_logger_1_1_validator_1_1_logger_configuration_validator_interface" ],
    [ "PsrLoggerConfigurationValidator", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_logger_1_1_validator_1_1_psr_logger_configuration_validator.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_logger_1_1_validator_1_1_psr_logger_configuration_validator" ]
];