var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_state =
[
    [ "ModuleStateIsAlreadySetException", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_state_1_1_module_state_is_already_set_exception.html", null ],
    [ "ModuleStateService", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_state_1_1_module_state_service.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_state_1_1_module_state_service" ],
    [ "ModuleStateServiceInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_state_1_1_module_state_service_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_state_1_1_module_state_service_interface" ]
];