var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_setting =
[
    [ "Event", "namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_setting_1_1_event.html", "namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_setting_1_1_event" ],
    [ "Setting", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_setting_1_1_setting.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_setting_1_1_setting" ],
    [ "SettingDao", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_setting_1_1_setting_dao.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_setting_1_1_setting_dao" ],
    [ "SettingDaoInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_setting_1_1_setting_dao_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_setting_1_1_setting_dao_interface" ]
];