var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_adapter =
[
    [ "ShopAdapter", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_adapter_1_1_shop_adapter.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_adapter_1_1_shop_adapter" ],
    [ "ShopAdapterInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_adapter_1_1_shop_adapter_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_adapter_1_1_shop_adapter_interface" ]
];