var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_event =
[
    [ "ShopConfigurationChangedEvent", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_event_1_1_shop_configuration_changed_event.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_event_1_1_shop_configuration_changed_event" ]
];