var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_common_1_1_database =
[
    [ "QueryBuilderFactory", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_common_1_1_database_1_1_query_builder_factory.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_common_1_1_database_1_1_query_builder_factory" ],
    [ "QueryBuilderFactoryInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_common_1_1_database_1_1_query_builder_factory_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_common_1_1_database_1_1_query_builder_factory_interface" ]
];