var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_utility =
[
    [ "ShopSettingEncoder", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_utility_1_1_shop_setting_encoder.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_utility_1_1_shop_setting_encoder" ],
    [ "ShopSettingEncoderInterface", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_utility_1_1_shop_setting_encoder_interface.html", "interface_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_config_1_1_utility_1_1_shop_setting_encoder_interface" ]
];