var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_common_1_1_factory =
[
    [ "ConnectionFactory", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_common_1_1_factory_1_1_connection_factory.html", "class_oxid_esales_1_1_eshop_community_1_1_internal_1_1_common_1_1_factory_1_1_connection_factory" ]
];