var namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_install =
[
    [ "DataObject", "namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_install_1_1_data_object.html", "namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_install_1_1_data_object" ],
    [ "Service", "namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_install_1_1_service.html", "namespace_oxid_esales_1_1_eshop_community_1_1_internal_1_1_framework_1_1_module_1_1_install_1_1_service" ]
];